name: Pytest CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }
        file: ./coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
        fail_ci_if_error: false #optional (default = false)
    - name: Setup Python Version
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Env Set Up
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir -p data
        mkdir -p model
    - name: Run Tests
      run: |
        pip install pytest
        pytest
